name: debian

on: [push, pull_request]

jobs:
  debian:
    name: Debian/Ubuntu
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        run: |
          ./build.sh 
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: debian
          path: ./*.deb
